### ISSUE TITLE
Thanks for the computer coaching today!

### ISSUE THREAD

**Issue by soraraso42** [REAPERali00/Tutoring#1]
Hi Ali, 
  This is Sora. Just want to say thank you for the coaching session today. Besides confirming that my right shift is forever 'lost', I learned a few new tricks, got valuable advice on how to stay organised, got pointers to nice resources and got to know someone really cool and super passionate about full stack dev!

**Comment by REAPERali00** [comment]
Hi Sora,
Glad I was able to help! It's always a pleasure to work with someone as passionate and eager to learn, I'm here to assist with any challenges or questions you might have. Wishing you the very best in all your future endeavors in your course! Keep up the fantastic work!
